### ISSUE TITLE
Stalls poke out from the underside of the cave. 

### ISSUE THREAD

**Issue by Mad-phil** [tunnelvr/tunnelvr#22]
When drawing a stall sometime they stick out underneath the cave. - Needs to be terminated at the cave floor.

**Comment by goatchurchprime** [comment]
I don't consider the stal definition finished enough to do this tidying up.  We might want a system to draw the bottom of the stal, or defining a stal forest.

**Comment by goatchurchprime** [comment]
the stal is obsolete, to be replaced by the cuboid boulder, which can have its face projected onto the floor
