### ISSUE TITLE
Gaurs and flowstone

### ISSUE THREAD

**Issue by Mad-phil** [tunnelvr/tunnelvr#24]
The ability to draw Gaurs/ flow stone, best by outlining the rim of the gaur/flow stone and it draw a curve (user defined or hyperbular?) to the cave floor or intersection with another object, stone, stall, wall etc.

**Comment by goatchurchprime** [comment]
We need to get what we would draw to define it first.  I have trialed it out in one section of jayadong

**Comment by goatchurchprime** [comment]
this is now ready to start testing to see if we have enough boulder drawing commands to make these shapes possible

**Comment by goatchurchprime** [comment]
There's something there that can do it now.  will need more specific issues posted for it
